using System.Text.Json;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
using HousecarlCore;
using HousecarlMcp;

namespace HousecarlGenerator;

/// <summary>
/// read_plugin_file guard — the standalone-copy chain's Stage-1 tool: a RAW, OUT-OF-LOAD-ORDER read of ONE plugin
/// file straight off disk, INCLUDING a plugin DISABLED in MO2. Proves the load-bearing behaviours:
///   1  locate + READ a plugin inside a DISABLED mod folder, by filename (the whole point — reach an inactive donor)
///   1b locate + READ a plugin in an UNLISTED mod folder — on disk but absent from modlist.txt, the state of a patch
///      houseCARL just wrote before the MO2 refresh registers it (HCBR-2026-07-14-02 gap 3: the write lane resolved
///      the fresh patch by bare filename while the read lane demanded an absolute path)
///   2  ENUMERATE a type the file defines (+ editorid_contains), and 3 the whole-file record-type SUMMARY
///   4  a DIRECT PATH read ("inspect any file")
///   5  the render stamps OUT-OF-LOAD-ORDER (the single load-bearing requirement) + read_record's `path = token` format
///   6  the declared-master-not-installed advisory (Q3)
///      (the ENABLED-flag arms for a DIRECT PATH — an enabled plugin's own file must not read as inactive, a
///       same-named backup outside the install must — live in bulk-primitives-wave3-guard's diff arm, which is
///       where the fixture with a real active order + an out-of-install backup already exists; #269)
///   7  Q3 refusals: missing filename, bad FormID, a FormID the file doesn't define, formid=+type= together, and an
///      AMBIGUOUS filename (surfaced + mod= disambiguates, never guessed)
///
/// Self-contained: one synthetic MO2 instance with real plugin bytes. The tool opens its OWN overlay and NEVER
/// touches the resolver index, so this needs no valid load order (loadorder.txt/plugins.txt are empty). Cleaned in finally.
/// </summary>
internal static class ReadPluginFileProbe
{
    [CiProbe("read-plugin-file-guard")]
    public static int RunGuard(string[] args)
    {
        Console.WriteLine("================================================================");
        Console.WriteLine(" read-plugin-file guard — raw, out-of-load-order reads (incl. DISABLED)");
        Console.WriteLine("================================================================");
        Console.WriteLine();
        int fail = 0;
        void Check(bool c, string label) { Console.WriteLine((c ? "  PASS  " : "  FAIL  ") + label); if (!c) fail++; }

        var root = Path.Combine(Path.GetTempPath(), "hc-readpluginfile-guard-" + Guid.NewGuid().ToString("N"));
        try
        {
            string instance = Path.Combine(root, "instance");
            string profiles = Path.Combine(instance, "profiles", "Default");
            string mods = Path.Combine(instance, "mods");
            string ovw = Path.Combine(instance, "overwrite");
            string data = Path.Combine(root, "game", "Data");
            Directory.CreateDirectory(profiles);
            Directory.CreateDirectory(ovw);
            Directory.CreateDirectory(data);
            foreach (var m in new[] { "DonorMod", "DupModA", "DupModB", "PatchMod", "ActiveMasterMod", "DisabledMasterMod" })
                Directory.CreateDirectory(Path.Combine(mods, m));

            File.WriteAllText(Path.Combine(instance, "ModOrganizer.ini"),
                "[General]\r\ngameName=Skyrim Special Edition\r\nselected_profile=@ByteArray(Default)\r\ngamePath=@ByteArray("
                + Path.Combine(root, "game").Replace(@"\", @"\\") + ")\r\n");

            // modlist.txt: DonorMod + DupModB + DisabledMasterMod DISABLED (the read-inactive targets); the rest enabled.
            File.WriteAllText(Path.Combine(profiles, "modlist.txt"),
                "# This file was automatically generated by Mod Organizer.\r\n+PatchMod\r\n+ActiveMasterMod\r\n+DupModA\r\n-DupModB\r\n-DisabledMasterMod\r\n-DonorMod\r\n");
            File.WriteAllText(Path.Combine(profiles, "loadorder.txt"), "# header\r\n");   // resolver is never built — empty is fine
            File.WriteAllText(Path.Combine(profiles, "plugins.txt"), "*HcRpfActive.esm\r\n");   // the one master that's ACTIVE (checked)

            // ---- the DISABLED donor: a keyword + two weapons (3 records / 2 types) ----
            var donorKey = new ModKey("Donor", ModType.Plugin);
            FormKey kwFk, swordFk;
            {
                var d = new SkyrimMod(donorKey, SkyrimRelease.SkyrimSE);
                var kw = d.Keywords.AddNew(); kw.EditorID = "DonorKw"; kwFk = kw.FormKey;
                var sword = d.Weapons.AddNew(); sword.EditorID = "DonorSword"; sword.BasicStats = new WeaponBasicStats { Damage = 12 }; swordFk = sword.FormKey;
                var axe = d.Weapons.AddNew(); axe.EditorID = "DonorAxe"; axe.BasicStats = new WeaponBasicStats { Damage = 15 };
                d.BeginWrite.ToPath(Path.Combine(mods, "DonorMod", donorKey.FileName.String)).WithLoadOrder(Array.Empty<ISkyrimModGetter>()).Write();
            }

            var store = new UserConfigStore(Path.Combine(root, "user.json"));
            using var svc = LoadOrderService.WithInstance(instance, 0, store);

            // 1 — locate + read a DISABLED donor by filename (the whole point)
            Console.WriteLine("--- 1: locate + read a plugin inside a DISABLED mod folder ---");
            var rd = svc.ReadPluginFile("Donor.esp", swordFk.ToString(), null, null, new[] { "BasicStats.Damage" }, 1, null, 500);
            Check(rd.Error is null && rd.Mode == "read", $"reads a disabled donor by filename — mode={rd.Mode}, err={rd.Error ?? "none"}");
            Check(rd.Record is not null && rd.Record.EditorId == "DonorSword", $"the FILE's own record — editorid={rd.Record?.EditorId ?? "?"}");
            Check(rd.Record is not null && rd.Record.Fields.Count == 1 && rd.Record.Fields[0].Token == "12",
                  $"field token round-trips like read_record — {(rd.Record is { Fields.Count: > 0 } ? rd.Record.Fields[0].Token : "?")}");
            Check(rd.Where is not null && rd.Where.Contains("DISABLED") && !rd.Enabled, $"located in a DISABLED mod, flagged not-active — where='{rd.Where}', enabled={rd.Enabled}");

            // 1b — locate + read a plugin in an UNLISTED mod folder (a fresh houseCARL patch before the MO2 refresh).
            //      The folder exists on disk but modlist.txt does NOT mention it — before the fix, the locate missed it
            //      and the bare-filename read errored "in no mod folder" while into= resolved the same file fine.
            Console.WriteLine("\n--- 1b: locate + read a plugin in an UNLISTED mod folder (pre-refresh houseCARL patch) ---");
            var unlistedKey = new ModKey("HcUnlisted", ModType.Plugin);
            FormKey unlistedFk;
            {
                Directory.CreateDirectory(Path.Combine(mods, "UnlistedPatch"));   // deliberately NOT added to modlist.txt
                var u = new SkyrimMod(unlistedKey, SkyrimRelease.SkyrimSE);
                var uw = u.Weapons.AddNew(); uw.EditorID = "UnlistedSword"; uw.BasicStats = new WeaponBasicStats { Damage = 9 }; unlistedFk = uw.FormKey;
                u.BeginWrite.ToPath(Path.Combine(mods, "UnlistedPatch", unlistedKey.FileName.String)).WithLoadOrder(Array.Empty<ISkyrimModGetter>()).Write();
            }
            var ur = svc.ReadPluginFile("HcUnlisted.esp", unlistedFk.ToString(), null, null, new[] { "BasicStats.Damage" }, 1, null, 500);
            Check(ur.Error is null && ur.Mode == "read" && ur.Record?.EditorId == "UnlistedSword",
                  $"reads an UNLISTED-folder plugin by bare filename — mode={ur.Mode}, editorid={ur.Record?.EditorId ?? "?"}, err={ur.Error ?? "none"}");
            Check(ur.Where is not null && ur.Where.Contains("UNLISTED") && !ur.Enabled,
                  $"located as UNLISTED, flagged not-active — where='{ur.Where}', enabled={ur.Enabled}");

            // 2 — enumerate a type the file defines (+ editorid_contains)
            Console.WriteLine("\n--- 2: enumerate a type the file defines ---");
            var en = svc.ReadPluginFile("Donor.esp", null, "Weapon", null, null, 1, null, 500);
            Check(en.Error is null && en.Mode == "enumerate" && en.RowTotal == 2, $"type=Weapon → 2 rows — mode={en.Mode}, total={en.RowTotal}, err={en.Error ?? "none"}");
            Check(en.Rows.Any(r => r.EditorId == "DonorSword") && en.Rows.Any(r => r.EditorId == "DonorAxe"), "both weapons enumerated");
            var enf = svc.ReadPluginFile("Donor.esp", null, "Weapon", null, null, 1, "Axe", 500);
            Check(enf.Mode == "enumerate" && enf.RowTotal == 1 && enf.Rows[0].EditorId == "DonorAxe", $"editorid_contains=Axe narrows to 1 — total={enf.RowTotal}");

            // 3 — whole-file record-type summary
            Console.WriteLine("\n--- 3: whole-file record-type summary ---");
            var su = svc.ReadPluginFile("Donor.esp", null, null, null, null, 1, null, 500);
            Check(su.Error is null && su.Mode == "summary" && su.RecordTotal == 3, $"3 records — mode={su.Mode}, total={su.RecordTotal}");
            Check(su.TypeCounts.Any(t => t.Type == "Keyword" && t.Count == 1) && su.TypeCounts.Any(t => t.Type == "Weapon" && t.Count == 2), "type counts: Keyword(1) + Weapon(2)");

            // 4 — direct-path read (inspect any file)
            Console.WriteLine("\n--- 4: direct-path read (inspect any file) ---");
            var dpath = Path.Combine(mods, "DonorMod", "Donor.esp");
            var dp = svc.ReadPluginFile(dpath, kwFk.ToString(), null, null, null, 1, null, 500);
            Check(dp.Error is null && dp.Mode == "read" && dp.Where == "direct path" && dp.Record?.EditorId == "DonorKw",
                  $"reads by absolute path — where='{dp.Where}', editorid={dp.Record?.EditorId ?? "?"}");

            // Arms 5 and 5b stood here — the text render's OUT-OF-LOAD-ORDER stamp and its `path = token` field
            // line, and the json render's validity, out_of_load_order/mode=read shape and matching field token.
            // All four drove housecarl_read_plugin_file, which the 1.x cut deleted. The stamp and the ambiguity
            // remedy were already covered by the converted records family; the field FORM and the json arms are
            // tests against housecarl_records' off-order source pole in src/housecarl-mcp-tests now. Every arm
            // above and below calls svc.ReadPluginFile — the service method, which is not deleted — and stands.

            // 6 — master advisory (Q3): each declared master classified by whether it will actually LOAD.
            //   6a missing  — installed NOWHERE in the install
            //   6b inactive — present ONLY in a DISABLED mod (the PR #148 false-negative: a disabled mod is NOT active,
            //                 so it must NOT be counted as satisfied — the fix this arm guards)
            //   6c active   — enabled + checked → satisfied, in NEITHER list
            // One Dependent.esp overrides a record from each of three masters, so a single read exercises all three.
            Console.WriteLine("\n--- 6: master advisory — missing / inactive(disabled) / active ---");
            var activeKey = new ModKey("HcRpfActive", ModType.Master);     // enabled mod + *checked in plugins.txt
            var disabledKey = new ModKey("HcRpfDisabled", ModType.Master); // present only in a DISABLED mod
            var ghostKey = new ModKey("HcRpfGhost", ModType.Master);       // installed nowhere
            string activePath = Path.Combine(mods, "ActiveMasterMod", activeKey.FileName.String);
            string disabledPath = Path.Combine(mods, "DisabledMasterMod", disabledKey.FileName.String);
            string ghostPath = Path.Combine(root, "ghost", ghostKey.FileName.String);
            Directory.CreateDirectory(Path.GetDirectoryName(ghostPath)!);
            foreach (var (mk, mp) in new[] { (activeKey, activePath), (disabledKey, disabledPath), (ghostKey, ghostPath) })
            {
                var g = new SkyrimMod(mk, SkyrimRelease.SkyrimSE);
                var gw = g.Weapons.AddNew(); gw.EditorID = mk.Name + "W"; gw.BasicStats = new WeaponBasicStats { Damage = 5 };
                g.BeginWrite.ToPath(mp).WithLoadOrder(Array.Empty<ISkyrimModGetter>()).Write();
            }
            var activeOv = SkyrimMod.CreateFromBinaryOverlay(activePath, SkyrimRelease.SkyrimSE);
            var disabledOv = SkyrimMod.CreateFromBinaryOverlay(disabledPath, SkyrimRelease.SkyrimSE);
            var ghostOv = SkyrimMod.CreateFromBinaryOverlay(ghostPath, SkyrimRelease.SkyrimSE);
            try
            {
                var dep = new SkyrimMod(new ModKey("Dependent", ModType.Plugin), SkyrimRelease.SkyrimSE);
                dep.Weapons.GetOrAddAsOverride(activeOv.Weapons.First());     // overriding each master's record declares it a master
                dep.Weapons.GetOrAddAsOverride(disabledOv.Weapons.First());
                dep.Weapons.GetOrAddAsOverride(ghostOv.Weapons.First());
                dep.BeginWrite.ToPath(Path.Combine(mods, "PatchMod", "Dependent.esp"))
                   .WithLoadOrder(new[] { (ISkyrimModGetter)activeOv, disabledOv, ghostOv }).Write();
            }
            finally { (activeOv as IDisposable)?.Dispose(); (disabledOv as IDisposable)?.Dispose(); (ghostOv as IDisposable)?.Dispose(); }
            var mm = svc.ReadPluginFile("Dependent.esp", null, null, null, null, 1, null, 500);
            Check(mm.Error is null && mm.Masters.Count == 3, $"declares 3 masters — [{string.Join(", ", mm.Masters)}]");
            Check(mm.MissingMasters.Count == 1 && mm.MissingMasters.Any(x => x.Equals("HcRpfGhost.esm", StringComparison.OrdinalIgnoreCase)),
                  $"6a the uninstalled master is MISSING — missing=[{string.Join(", ", mm.MissingMasters)}]");
            Check(mm.InactiveMasters.Count == 1 && mm.InactiveMasters.Any(x => x.Equals("HcRpfDisabled.esm", StringComparison.OrdinalIgnoreCase)),
                  $"6b the disabled-mod-only master is INACTIVE, NOT satisfied (the fixed false-negative) — inactive=[{string.Join(", ", mm.InactiveMasters)}]");
            Check(!mm.MissingMasters.Concat(mm.InactiveMasters).Any(x => x.Equals("HcRpfActive.esm", StringComparison.OrdinalIgnoreCase)),
                  "6c the enabled+checked master is satisfied — in neither list");
            // The render arm for 6 stood here — that both advisory lines reach the rendered read. It drove
            // housecarl_read_plugin_file and dies with it, and it has NO replacement: the advisory is written
            // only by that tool's own renderer, and the records surface says nothing about a read file's
            // declared masters. The three classification arms above ask the service and stand.

            // 7 — Q3 refusals (never a silent wrong answer)
            Console.WriteLine("\n--- 7: Q3 refusals ---");
            var miss = svc.ReadPluginFile("Nope.esp", null, null, null, null, 1, null, 500);
            Check(miss.Mode == "error" && (miss.Error?.Contains("no mod folder") ?? false), $"a missing filename is refused, named — {miss.Error ?? "(no error!)"}");

            var badfk = svc.ReadPluginFile("Donor.esp", "zzzzzz", null, null, null, 1, null, 500);
            Check(badfk.Mode == "error" && (badfk.Error?.Contains("bad FormID") ?? false), $"a bad FormID is refused — {badfk.Error ?? "(no error!)"}");

            var notdef = svc.ReadPluginFile("Donor.esp", "FFFFFF:Skyrim.esm", null, null, null, 1, null, 500);
            Check(notdef.Mode == "error" && (notdef.Error?.Contains("does not define") ?? false), $"a FormID the file doesn't define is refused — {notdef.Error ?? "(no error!)"}");

            var both = svc.ReadPluginFile("Donor.esp", swordFk.ToString(), "Weapon", null, null, 1, null, 500);
            Check(both.Mode == "error" && (both.Error?.Contains("EITHER") ?? false), $"formid= + type= together is refused — {both.Error ?? "(no error!)"}");

            // 7b — ambiguous filename → surfaced, mod= disambiguates
            Console.WriteLine("\n--- 7b: ambiguous filename → surfaced, mod= disambiguates ---");
            var dupKey = new ModKey("Dup", ModType.Plugin);
            foreach (var (folder, eid) in new[] { ("DupModA", "DupEnabledW"), ("DupModB", "DupDisabledW") })
            {
                var du = new SkyrimMod(dupKey, SkyrimRelease.SkyrimSE);
                var dw = du.Weapons.AddNew(); dw.EditorID = eid; dw.BasicStats = new WeaponBasicStats { Damage = 7 };
                du.BeginWrite.ToPath(Path.Combine(mods, folder, dupKey.FileName.String)).WithLoadOrder(Array.Empty<ISkyrimModGetter>()).Write();
            }
            var amb = svc.ReadPluginFile("Dup.esp", null, "Weapon", null, null, 1, null, 500);
            Check(amb.Mode == "ambiguous" && amb.Ambiguous.Count == 2, $"a name in 2 folders is AMBIGUOUS, not guessed — mode={amb.Mode}, hits={amb.Ambiguous.Count}");
            // The render arm here — that the ambiguity render tells the caller to pass mod= — drove
            // housecarl_read_plugin_file. The records surface refuses the same way, and RecordsDuplicateFilenameTests
            // in src/housecarl-mcp-tests already covered it before the cut.
            var disamb = svc.ReadPluginFile("Dup.esp", null, "Weapon", "DupModB", null, 1, null, 500);
            Check(disamb.Mode == "enumerate" && disamb.Rows.Count == 1 && disamb.Rows[0].EditorId == "DupDisabledW",
                  $"mod=DupModB reads THAT copy — editorid={(disamb.Rows.Count > 0 ? disamb.Rows[0].EditorId : "?")}");

            // 7c — the ground under SPEC §5.5's exemption: S1 poles stay BARE (`source=winner`, not `*winner`)
            //      because a plugin name is extension-mandatory and so can never equal a bare pole word. That is a
            //      property of this name space, and it holds only while an extensionless spelling fails to name a
            //      plugin. If the surface ever fuzzy-matches "Donor" to "Donor.esp", the exemption lapses and the
            //      S1 poles need the sigil — so the amendment's ground is pinned here rather than asserted in a doc.
            Console.WriteLine("\n--- 7c: an extensionless plugin spelling refuses by name (SPEC §5.5's exemption ground) ---");
            var bare = svc.ReadPluginFile("Donor", null, "Weapon", null, null, 1, null, 500);
            Check(bare.Mode == "error", $"'Donor' (no extension) does NOT resolve to Donor.esp — mode={bare.Mode}");
            Check(bare.Rows.Count == 0, $"…and returns no rows — a near-miss never reads a real plugin's records ({bare.Rows.Count} rows)");
            Check(bare.Error is not null && bare.Error.Contains("Donor", StringComparison.OrdinalIgnoreCase),
                  $"…and the refusal names what it could not find — {bare.Error ?? "(no error!)"}");
            // The control: the SAME name WITH its extension does resolve, so the refusal above is the missing
            // extension and not a broken fixture.
            var withExt = svc.ReadPluginFile("Donor.esp", null, "Weapon", null, null, 1, null, 500);
            Check(withExt.Mode == "enumerate" && withExt.Rows.Count > 0,
                  $"…while 'Donor.esp' reads normally — the refusal is the extension, not the fixture (mode={withExt.Mode}, rows={withExt.Rows.Count})");
        }
        finally { try { Directory.Delete(root, recursive: true); } catch { /* temp scratch */ } }

        Console.WriteLine();
        Console.WriteLine(fail == 0 ? "================ ALL PASS ================" : $"================ {fail} CHECK(S) FAILED ================");
        return fail == 0 ? 0 : 1;
    }
}
