using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
using HousecarlCore;
using HousecarlMcp;

namespace HousecarlGenerator;

/// <summary>
/// read_plugin_file guard — the standalone-copy chain's Stage-1 tool: a RAW, OUT-OF-LOAD-ORDER read of ONE plugin
/// file straight off disk, INCLUDING a plugin DISABLED in MO2. Proves the load-bearing behaviours:
///   1  locate + READ a plugin inside a DISABLED mod folder, by filename (the whole point — reach an inactive donor)
///   2  ENUMERATE a type the file defines (+ editorid_contains), and 3 the whole-file record-type SUMMARY
///   4  a DIRECT PATH read ("inspect any file")
///   5  the render stamps OUT-OF-LOAD-ORDER (the single load-bearing requirement) + read_record's `path = token` format
///   6  the declared-master-not-installed advisory (Q3)
///   7  Q3 refusals: missing filename, bad FormID, a FormID the file doesn't define, formid=+type= together, and an
///      AMBIGUOUS filename (surfaced + mod= disambiguates, never guessed)
///
/// Self-contained: one synthetic MO2 instance with real plugin bytes. The tool opens its OWN overlay and NEVER
/// touches the resolver index, so this needs no valid load order (loadorder.txt/plugins.txt are empty). Cleaned in finally.
/// </summary>
internal static class ReadPluginFileProbe
{
    public static int RunGuard(string[] args)
    {
        Console.WriteLine("================================================================");
        Console.WriteLine(" read-plugin-file guard — raw, out-of-load-order reads (incl. DISABLED)");
        Console.WriteLine("================================================================");
        Console.WriteLine();
        int fail = 0;
        void Check(bool c, string label) { Console.WriteLine((c ? "  PASS  " : "  FAIL  ") + label); if (!c) fail++; }

        var root = Path.Combine(Path.GetTempPath(), "hc-readpluginfile-guard-" + Guid.NewGuid().ToString("N"));
        try
        {
            string instance = Path.Combine(root, "instance");
            string profiles = Path.Combine(instance, "profiles", "Default");
            string mods = Path.Combine(instance, "mods");
            string ovw = Path.Combine(instance, "overwrite");
            string data = Path.Combine(root, "game", "Data");
            Directory.CreateDirectory(profiles);
            Directory.CreateDirectory(ovw);
            Directory.CreateDirectory(data);
            foreach (var m in new[] { "DonorMod", "DupModA", "DupModB", "PatchMod" })
                Directory.CreateDirectory(Path.Combine(mods, m));

            File.WriteAllText(Path.Combine(instance, "ModOrganizer.ini"),
                "[General]\r\ngameName=Skyrim Special Edition\r\nselected_profile=@ByteArray(Default)\r\ngamePath=@ByteArray("
                + Path.Combine(root, "game").Replace(@"\", @"\\") + ")\r\n");

            // modlist.txt: DonorMod + DupModB DISABLED (the read-inactive targets); DupModA + PatchMod enabled.
            File.WriteAllText(Path.Combine(profiles, "modlist.txt"),
                "# This file was automatically generated by Mod Organizer.\r\n+PatchMod\r\n+DupModA\r\n-DupModB\r\n-DonorMod\r\n");
            File.WriteAllText(Path.Combine(profiles, "loadorder.txt"), "# header\r\n");   // resolver is never built — empty is fine
            File.WriteAllText(Path.Combine(profiles, "plugins.txt"), "");

            // ---- the DISABLED donor: a keyword + two weapons (3 records / 2 types) ----
            var donorKey = new ModKey("Donor", ModType.Plugin);
            FormKey kwFk, swordFk;
            {
                var d = new SkyrimMod(donorKey, SkyrimRelease.SkyrimSE);
                var kw = d.Keywords.AddNew(); kw.EditorID = "DonorKw"; kwFk = kw.FormKey;
                var sword = d.Weapons.AddNew(); sword.EditorID = "DonorSword"; sword.BasicStats = new WeaponBasicStats { Damage = 12 }; swordFk = sword.FormKey;
                var axe = d.Weapons.AddNew(); axe.EditorID = "DonorAxe"; axe.BasicStats = new WeaponBasicStats { Damage = 15 };
                d.BeginWrite.ToPath(Path.Combine(mods, "DonorMod", donorKey.FileName.String)).WithLoadOrder(Array.Empty<ISkyrimModGetter>()).Write();
            }

            var store = new UserConfigStore(Path.Combine(root, "user.json"));
            using var svc = LoadOrderService.WithInstance(instance, 0, store);

            // 1 — locate + read a DISABLED donor by filename (the whole point)
            Console.WriteLine("--- 1: locate + read a plugin inside a DISABLED mod folder ---");
            var rd = svc.ReadPluginFile("Donor.esp", swordFk.ToString(), null, null, new[] { "BasicStats.Damage" }, 1, null, 500);
            Check(rd.Error is null && rd.Mode == "read", $"reads a disabled donor by filename — mode={rd.Mode}, err={rd.Error ?? "none"}");
            Check(rd.Record is not null && rd.Record.EditorId == "DonorSword", $"the FILE's own record — editorid={rd.Record?.EditorId ?? "?"}");
            Check(rd.Record is not null && rd.Record.Fields.Count == 1 && rd.Record.Fields[0].Token == "12",
                  $"field token round-trips like read_record — {(rd.Record is { Fields.Count: > 0 } ? rd.Record.Fields[0].Token : "?")}");
            Check(rd.Where is not null && rd.Where.Contains("DISABLED") && !rd.Enabled, $"located in a DISABLED mod, flagged not-active — where='{rd.Where}', enabled={rd.Enabled}");

            // 2 — enumerate a type the file defines (+ editorid_contains)
            Console.WriteLine("\n--- 2: enumerate a type the file defines ---");
            var en = svc.ReadPluginFile("Donor.esp", null, "Weapon", null, null, 1, null, 500);
            Check(en.Error is null && en.Mode == "enumerate" && en.RowTotal == 2, $"type=Weapon → 2 rows — mode={en.Mode}, total={en.RowTotal}, err={en.Error ?? "none"}");
            Check(en.Rows.Any(r => r.EditorId == "DonorSword") && en.Rows.Any(r => r.EditorId == "DonorAxe"), "both weapons enumerated");
            var enf = svc.ReadPluginFile("Donor.esp", null, "Weapon", null, null, 1, "Axe", 500);
            Check(enf.Mode == "enumerate" && enf.RowTotal == 1 && enf.Rows[0].EditorId == "DonorAxe", $"editorid_contains=Axe narrows to 1 — total={enf.RowTotal}");

            // 3 — whole-file record-type summary
            Console.WriteLine("\n--- 3: whole-file record-type summary ---");
            var su = svc.ReadPluginFile("Donor.esp", null, null, null, null, 1, null, 500);
            Check(su.Error is null && su.Mode == "summary" && su.RecordTotal == 3, $"3 records — mode={su.Mode}, total={su.RecordTotal}");
            Check(su.TypeCounts.Any(t => t.Type == "Keyword" && t.Count == 1) && su.TypeCounts.Any(t => t.Type == "Weapon" && t.Count == 2), "type counts: Keyword(1) + Weapon(2)");

            // 4 — direct-path read (inspect any file)
            Console.WriteLine("\n--- 4: direct-path read (inspect any file) ---");
            var dpath = Path.Combine(mods, "DonorMod", "Donor.esp");
            var dp = svc.ReadPluginFile(dpath, kwFk.ToString(), null, null, null, 1, null, 500);
            Check(dp.Error is null && dp.Mode == "read" && dp.Where == "direct path" && dp.Record?.EditorId == "DonorKw",
                  $"reads by absolute path — where='{dp.Where}', editorid={dp.Record?.EditorId ?? "?"}");

            // 5 — render stamps OUT-OF-LOAD-ORDER (end-to-end through the tool)
            Console.WriteLine("\n--- 5: render stamps OUT-OF-LOAD-ORDER ---");
            var render = ReadTools.ReadPluginFile(svc, "Donor.esp", swordFk.ToString(), null, null, new[] { "BasicStats.Damage" }, 1, null, 500, 0);
            Check(render.Contains("OUT-OF-LOAD-ORDER"), "the rendered read is stamped OUT-OF-LOAD-ORDER (the load-bearing requirement)");
            Check(render.Contains("BasicStats.Damage = 12"), "…and shows the field line in read_record's `path = token` format");

            // 6 — declared-master-not-installed advisory (Q3)
            Console.WriteLine("\n--- 6: declared-master-not-installed advisory ---");
            var ghostKey = new ModKey("HcRpfGhost", ModType.Master);
            string ghostPath = Path.Combine(root, "ghost", ghostKey.FileName.String);
            Directory.CreateDirectory(Path.GetDirectoryName(ghostPath)!);
            {
                var g = new SkyrimMod(ghostKey, SkyrimRelease.SkyrimSE);
                var gw = g.Weapons.AddNew(); gw.EditorID = "GhostW"; gw.BasicStats = new WeaponBasicStats { Damage = 5 };
                g.BeginWrite.ToPath(ghostPath).WithLoadOrder(Array.Empty<ISkyrimModGetter>()).Write();
            }
            var ghostOv = SkyrimMod.CreateFromBinaryOverlay(ghostPath, SkyrimRelease.SkyrimSE);
            try
            {
                var patchKey = new ModKey("Patch", ModType.Plugin);
                var p = new SkyrimMod(patchKey, SkyrimRelease.SkyrimSE);
                p.Weapons.GetOrAddAsOverride(ghostOv.Weapons.First());     // overriding a ghost record declares HcRpfGhost.esm a master
                p.BeginWrite.ToPath(Path.Combine(mods, "PatchMod", patchKey.FileName.String)).WithLoadOrder(new[] { (ISkyrimModGetter)ghostOv }).Write();
            }
            finally { (ghostOv as IDisposable)?.Dispose(); }               // release the lock so cleanup can delete it; ghost is NEVER installed in the instance
            var mm = svc.ReadPluginFile("Patch.esp", null, null, null, null, 1, null, 500);
            Check(mm.Error is null && mm.Masters.Any(x => x.Equals("HcRpfGhost.esm", StringComparison.OrdinalIgnoreCase)),
                  $"the patch declares HcRpfGhost.esm a master — [{string.Join(", ", mm.Masters)}]");
            Check(mm.MissingMasters.Any(x => x.Equals("HcRpfGhost.esm", StringComparison.OrdinalIgnoreCase)),
                  $"…and it is flagged NOT installed — missing=[{string.Join(", ", mm.MissingMasters)}]");

            // 7 — Q3 refusals (never a silent wrong answer)
            Console.WriteLine("\n--- 7: Q3 refusals ---");
            var miss = svc.ReadPluginFile("Nope.esp", null, null, null, null, 1, null, 500);
            Check(miss.Mode == "error" && (miss.Error?.Contains("no mod folder") ?? false), $"a missing filename is refused, named — {miss.Error ?? "(no error!)"}");

            var badfk = svc.ReadPluginFile("Donor.esp", "zzzzzz", null, null, null, 1, null, 500);
            Check(badfk.Mode == "error" && (badfk.Error?.Contains("bad FormID") ?? false), $"a bad FormID is refused — {badfk.Error ?? "(no error!)"}");

            var notdef = svc.ReadPluginFile("Donor.esp", "FFFFFF:Skyrim.esm", null, null, null, 1, null, 500);
            Check(notdef.Mode == "error" && (notdef.Error?.Contains("does not define") ?? false), $"a FormID the file doesn't define is refused — {notdef.Error ?? "(no error!)"}");

            var both = svc.ReadPluginFile("Donor.esp", swordFk.ToString(), "Weapon", null, null, 1, null, 500);
            Check(both.Mode == "error" && (both.Error?.Contains("EITHER") ?? false), $"formid= + type= together is refused — {both.Error ?? "(no error!)"}");

            // 7b — ambiguous filename → surfaced, mod= disambiguates
            Console.WriteLine("\n--- 7b: ambiguous filename → surfaced, mod= disambiguates ---");
            var dupKey = new ModKey("Dup", ModType.Plugin);
            foreach (var (folder, eid) in new[] { ("DupModA", "DupEnabledW"), ("DupModB", "DupDisabledW") })
            {
                var du = new SkyrimMod(dupKey, SkyrimRelease.SkyrimSE);
                var dw = du.Weapons.AddNew(); dw.EditorID = eid; dw.BasicStats = new WeaponBasicStats { Damage = 7 };
                du.BeginWrite.ToPath(Path.Combine(mods, folder, dupKey.FileName.String)).WithLoadOrder(Array.Empty<ISkyrimModGetter>()).Write();
            }
            var amb = svc.ReadPluginFile("Dup.esp", null, "Weapon", null, null, 1, null, 500);
            Check(amb.Mode == "ambiguous" && amb.Ambiguous.Count == 2, $"a name in 2 folders is AMBIGUOUS, not guessed — mode={amb.Mode}, hits={amb.Ambiguous.Count}");
            var ambRender = ReadTools.ReadPluginFile(svc, "Dup.esp", null, "Weapon", null, null, 1, null, 500, 0);
            Check(ambRender.Contains("mod="), "…and the render tells the caller to pass mod=");
            var disamb = svc.ReadPluginFile("Dup.esp", null, "Weapon", "DupModB", null, 1, null, 500);
            Check(disamb.Mode == "enumerate" && disamb.Rows.Count == 1 && disamb.Rows[0].EditorId == "DupDisabledW",
                  $"mod=DupModB reads THAT copy — editorid={(disamb.Rows.Count > 0 ? disamb.Rows[0].EditorId : "?")}");
        }
        finally { try { Directory.Delete(root, recursive: true); } catch { /* temp scratch */ } }

        Console.WriteLine();
        Console.WriteLine(fail == 0 ? "================ ALL PASS ================" : $"================ {fail} CHECK(S) FAILED ================");
        return fail == 0 ? 0 : 1;
    }
}
