namespace HousecarlCore;

/// <summary>
/// Every tool name the shipped surface uses, as compile-time constants -- the one home for the
/// <c>housecarl_</c> spellings (RUN_ORDER amendment 2026-09-02 base (i), #475).
///
/// <para><b>What this buys.</b> Deleting a tool means deleting its constant, and the compiler then
/// names every surviving site that still refers to it. The 1.x cut's checklist becomes a build-error
/// list rather than a population somebody noticed by hand -- which is the root both of PR #474's
/// class-stops shared.</para>
///
/// <para><b><c>const</c>, not <c>static readonly</c>.</b> These are spliced into
/// <c>[McpServerTool(Name = ...)]</c> and <c>[Description(...)]</c> arguments, which must be constant
/// expressions. <c>"..." + ToolNames.Records + "..."</c> is one; a <c>static readonly</c> field is not.</para>
///
/// <para><b>Why <c>housecarl-core</c> and not <c>housecarl-mcp</c>.</b> 25 of the 279 shipped sites are in
/// <c>housecarl-core</c>, and the project reference runs mcp -> core, so a registry in mcp could not reach
/// them. Placement follows the derived population, not the other way round.</para>
///
/// <para><b>The population is DECLARED, not registered.</b> One constant per <c>[McpServerTool].Name</c> on
/// the surface. That is deliberately not the set the SDK scans, which also needs <c>[McpServerToolType]</c>
/// on the declaring type: <c>housecarl_check</c> is declared and has never been registered (#470), its
/// attribute still names it in source, and it is owed a constant all the same.</para>
///
/// <para><b>Retired spellings are absent on purpose.</b> A name that no longer names a tool has no constant
/// whose deletion should break anything, and a second, hand-kept population is the hazard this file exists to
/// remove. The six retired 1.x write names stay literals in <c>AliasTable</c>'s retired rows.</para>
///
/// <para>GENERATED by <c>scripts/tool-names/sweep-tool-names.py --emit-registry</c>. Re-run it rather than
/// editing by hand; a new tool's constant arrives with its attribute.</para>
/// </summary>
public static class ToolNames
{
    public const string Apply = "housecarl_apply";
    public const string AssetStatus = "housecarl_asset_status";
    public const string BatchRecordDetail = "housecarl_batch_record_detail";  // deletion-flagged (rule 10(a)) -- dies at the 1.x cut
    public const string BsaExtract = "housecarl_bsa_extract";
    public const string BsaList = "housecarl_bsa_list";
    public const string BsaRepack = "housecarl_bsa_repack";
    public const string BulkPlaceAsset = "housecarl_bulk_place_asset";
    public const string Check = "housecarl_check";
    public const string CheckErrors = "housecarl_check_errors";  // deletion-flagged (rule 10(a)) -- dies at the 1.x cut
    public const string CompactPlugin = "housecarl_compact_plugin";
    public const string CompileScript = "housecarl_compile_script";
    public const string Copy = "housecarl_copy";
    public const string CopyNpcAppearance = "housecarl_copy_npc_appearance";
    public const string Create = "housecarl_create";
    public const string CreatePlugin = "housecarl_create_plugin";
    public const string CrossPluginQuery = "housecarl_cross_plugin_query";  // deletion-flagged (rule 10(a)) -- dies at the 1.x cut
    public const string DecompileScript = "housecarl_decompile_script";
    public const string DiffRecord = "housecarl_diff_record";  // deletion-flagged (rule 10(a)) -- dies at the 1.x cut
    public const string EffectChain = "housecarl_effect_chain";  // deletion-flagged (rule 10(a)) -- dies at the 1.x cut
    public const string Forward = "housecarl_forward";
    public const string LoadOrderStatus = "housecarl_load_order_status";
    public const string MergePlugins = "housecarl_merge_plugins";
    public const string NativePairingAudit = "housecarl_native_pairing_audit";
    public const string NexusCheckUpdates = "housecarl_nexus_check_updates";
    public const string NexusGraphql = "housecarl_nexus_graphql";
    public const string NexusIdentify = "housecarl_nexus_identify";
    public const string NexusMod = "housecarl_nexus_mod";
    public const string NexusSearch = "housecarl_nexus_search";
    public const string NifInspect = "housecarl_nif_inspect";
    public const string NifSet = "housecarl_nif_set";
    public const string PlaceAsset = "housecarl_place_asset";
    public const string ReadPluginFile = "housecarl_read_plugin_file";  // deletion-flagged (rule 10(a)) -- dies at the 1.x cut
    public const string ReadRecord = "housecarl_read_record";  // deletion-flagged (rule 10(a)) -- dies at the 1.x cut
    public const string Records = "housecarl_records";
    public const string Remove = "housecarl_remove";
    public const string Resolve = "housecarl_resolve";  // deletion-flagged (rule 10(a)) -- dies at the 1.x cut
    public const string SetMo2Instance = "housecarl_set_mo2_instance";
    public const string SetToolPath = "housecarl_set_tool_path";
    public const string SkseConfigAudit = "housecarl_skse_config_audit";
    public const string SkseInventory = "housecarl_skse_inventory";
    public const string SkypatcherLayer = "housecarl_skypatcher_layer";
    public const string SkypatcherRead = "housecarl_skypatcher_read";  // deletion-flagged (rule 10(a)) -- dies at the 1.x cut
    public const string UpdateStatus = "housecarl_update_status";
    public const string ValidateDialogue = "housecarl_validate_dialogue";  // deletion-flagged (rule 10(a)) -- dies at the 1.x cut
    public const string ValidateScripts = "housecarl_validate_scripts";  // deletion-flagged (rule 10(a)) -- dies at the 1.x cut
    public const string WriteSeq = "housecarl_write_seq";
}
